# Use `conda-build-prepare` before building for a better version string.
{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('v', '')|replace('-', '')|default('0.X'), GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH|default('gUNKNOWN')) %}

{% set python_version = PYTHON_VERSION | default('3.7') %}
{% set py_suffix = 'py%s'|format(python_version|replace('.', '')) %}
{% set lemon_version = '1.3.1' %}
{% set lemon_md5 = '1ff3c2d022168c82aa82a50d9d1ace73' %}
{% set cudd_version = '3.0.0' %}
{% set cudd_md5 = 'f81874f0fa8aac9905f0f4aed36ecd05' %}
{% set or_tools_version = '9.11' %}
{% set or_tools_md5 = '08cedd17bd148118439ff9f7d546ccaf' %}
package:
  name: openroad
  version: {{ version }}

source:
  - git_url: https://github.com/The-OpenROAD-Project/OpenROAD.git
    git_rev: b16bda7
    patches:
      - openroad-fmt-9.1_b16bda7e.patch
    #   - openroad-fmt-9.1.patch
  - url: https://github.com/The-OpenROAD-Project/lemon-graph/archive/refs/tags/{{ lemon_version }}.tar.gz
    md5: {{ lemon_md5 }}
    folder: third_party/lemon
  - url: https://github.com/The-OpenROAD-Project/cudd/archive/refs/tags/{{ cudd_version }}.tar.gz
    md5: {{ cudd_md5 }}
    folder: third_party/cudd
  - url:     https://github.com/google/or-tools/archive/refs/tags/v{{ or_tools_version }}.tar.gz
    md5: {{ or_tools_md5 }}
    folder: third_party/or-tools
build:
  # number: 202202031935
  number: {{ environ.get('DATE_NUM') }}
  # string: 20220203_1935_py37
  string: {{ environ.get('DATE_STR') }}_{{ py_suffix }}
  script_env:
    - CI
  ignore_run_exports_from:
    # header-only libraries
    - fmt

requirements:
  build:
    - make
    - cmake >=3.19
    - swig 4.0.2
    - bison
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('libxau-devel') }}         # [linux]
    - {{ cdt('libxext-devel') }}        # [linux]
    - {{ cdt('libxdamage-devel') }}     # [linux]
    - {{ cdt('libxfixes-devel') }}      # [linux]
    - {{ cdt('libxxf86vm-devel') }}     # [linux]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}     # [linux]
    - {{ cdt('libselinux-devel') }}     # [linux]
  host:
    - python {{ python_version }}
    - libboost 1.82
    - eigen 3.3
    - spdlog 1.11
    - tk
    - zlib
    - fmt 9.1
    - libgomp                 [not osx]
    - llvm-openmp             [osx]
    - qt >=5.7,<6
    - libxcb
  run:
    # missing run_exports
    - {{ pin_compatible('libboost', min_pin='x.x', max_pin='x.x') }}
    - {{ pin_compatible('python', min_pin='x.x', max_pin='x.x') }}
    - qt-main >=5.7,<6
    - spdlog >=1.11,<1.12
    - libxcb

test:
  commands:
    - openroad -version
    - sta -version

about:
  home: https://theopenroadproject.org/
  license: BSD-3-Clause
  summary: OpenROAD is an unified application implementing an RTL-to-GDS Flow.

extra:
  recipe-maintainers:
    - proppy
